services:
  prometheus:
    image: prom/prometheus:v3.14.0
    ports:
      - "127.0.0.1:9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prometheus-data:/prometheus

  alertmanager:
    image: prom/alertmanager:v0.28.1
    restart: unless-stopped
    volumes:
      - ./alertmanager:/etc/alertmanager:ro

  grafana:
    image: grafana/grafana:12.2.0
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

  nginx:
    image: nginx:1.29.1-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - grafana
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  prometheus-data:
  grafana-data: